version: 0.0
os: linux
files:
  - source: /build/libs/
    destination: /opt/tomcat/webapps
hooks:
  BeforeInstall:
    - location: codedeploy-scripts/beforeinstall.sh
      timeout: 300
      runas: root
  
  ApplicationStop:
    - location: codedeploy-scripts/stop.sh
      timeout: 300
      runas: root
        
  ApplicationStart:
    - location: codedeploy-scripts/start.sh
      timeout: 300
      runas: root
